apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-whoami

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: {{ .Release.Name }}-whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-whoami
  labels:
    app: {{ .Release.Name }}-whoami

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-whoami
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          env:
            - name: WHOAMI_NAME
              value: {{ .Values.whoami.name | default "default_template_name" }}
          ports:
            - name: web
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-whoami-ingress
  # annotations:
  #   traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ .Values.whoami.domain | default "whoami.k8s.orb.local" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-whoami
            port:
              name: web